### ISSUE TITLE
How to access USERDATA_BASE?

### ISSUE THREAD

**Issue by krikkirk** [OpenEPaperLink/Tag_FW_EFR32xG22#2]
Hi there, unlike other xg22 tags, there is no button eink nfc GPIOs defined for displaydata epl. I am wondering how are they passed to the firmware. Are they from USERDATA_BASE? If so how can I read the USERDATA_BASE? Also how you distinguished the two variants of displaydata epl in your firmware. Thanks for your effort.

**Comment by atc1441** [comment]
Hey,
What display do you have? 
Any picture? 
Note that not all are supported or allowed here ;)

**Comment by stevew817** [comment]
Hi @krikkirk - I don't have full support for DisplayData tags yet, as I haven't been able to deduce the pinout from the FCC database pictures. If you can get high-quality pictures of the PCB, front and back, of the tag(s) you have, then I can take a stab at adding actual support instead of just a shim :)

**Comment by krikkirk** [comment]
@stevew817 Thanks for the info. I don't have them either. I was curious because DisplayData FWs will be generated from your code. It's all clear now. 
I do have a Newton M3 2.9 with BG22. However, the autodetect fails to recognize the third color capability. If I manually specify the color, controller, and resolution, it displays "Newton M3 2.2" in the third color. I assume USERDATA_BASE is similar to UICR from the NRF chip family, but I don't know how to access it. If I can gain access to USERDATA_BASE, we can improve the auto-recognition of the tags.

**Comment by stevew817** [comment]
Gotcha. Let's find out what's happening with your tag.

Do you have a JLink-compatible debugger? The easiest way to read out UserData would be using Simplicity Commander (comes with Simplicity Studio or as [a standalone utility](https://www.silabs.com/developers/simplicity-studio/simplicity-commander?tab=downloads)), and giving it the command `commander readmem --device EFR32BG22CxxxF352 --region "@userdata"`

**Comment by krikkirk** [comment]
@stevew817 Thanks for the helpful command. Here is the [user data](https://github.com/user-attachments/files/16405572/userdata.txt) I got from it. I scrambled the MAC address, but everything else is the original data.
[userdata.txt](https://github.com/user-attachments/files/16405572/userdata.txt)
[Here is the fcc report](https://fcc.report/FCC-ID/2AFWN-EL029F4WRC)

**Comment by stevew817** [comment]
@krikkirk Is your Newton a BWR, BWY or BWRY color type? The autodection isn't detecting your third color as byte 0x0A in the UICR/UserData is set to '2' instead of '1' ('1' is expected for BWR tags). See https://github.com/OpenEPaperLink/Tag_FW_EFR32xG22/blob/bea011e24d4bac65a920aeaf2c16e460aa4f0813/firmware/oepl_efr32_hwtypes.c#L460

As for the other parameters, the controller should be autodetected as SSD based on byte 0x09 = 0x15, and resolution should be set correctly to 384x168 based on bytes [0x0C:0x0B] and [0x0E:0x0D]. Tagtype in byte 0x16 is set to 0x42, which [should resolve to M3 2.9"](https://github.com/OpenEPaperLink/Tag_FW_EFR32xG22/blob/bea011e24d4bac65a920aeaf2c16e460aa4f0813/firmware/oepl_efr32_hwtypes.c#L358).

If you have the capability of building firmware yourself, I'd say try changing the line [here](https://github.com/OpenEPaperLink/Tag_FW_EFR32xG22/blob/bea011e24d4bac65a920aeaf2c16e460aa4f0813/firmware/oepl_efr32_hwtypes.c#L460) to set `have_thirdcolor` if `solum_colortype` is 1 or 2, not just if it's uneven. Build, erase your device, flash with the combined bootloader+firmware file `full_binaries/v4/SOLUM_AUTODETECT_FULL_v4.s37]` and report back with your findings :)

**Comment by krikkirk** [comment]
@stevew817  It is a BWY type. I changed line 460 to `(solum_colortype == 1 || solum_colortype == 2) ;` and It did bring up the third color. The only nitpick is that the string under `OpenEPaperLink` is `Newton M3 2.2''` instead of `Newton M3 2.9''` but it is not a big deal. Thank you for your input!

**Comment by krikkirk** [comment]
@stevew817 I have one more question, there two places that define the debug pins. 
One is https://github.com/OpenEPaperLink/Tag_FW_EFR32xG22/blob/bea011e24d4bac65a920aeaf2c16e460aa4f0813/firmware/sl_iostream_eusart_euart_debug_config.h#L94
, the other one is 
https://github.com/OpenEPaperLink/Tag_FW_EFR32xG22/blob/bea011e24d4bac65a920aeaf2c16e460aa4f0813/firmware/oepl_efr32_hwtypes.c#L230
They don't match, so which one should I follow? Also, how can I read the debug output? Thanks!

**Comment by stevew817** [comment]
> They don't match, so which one should I follow? Also, how can I read the debug output? Thanks!

The config in `oepl_efr32_hwtypes.c` is used. You will note that pin B5 (from the sl_* header) doesn't exist on this chip - the file is solely there to satisfy the SDK such that it pulls in the code needed for setting up and using the EUART. The actual setup is done here as long as the tag's config declares the debug type as DBG_EUART: https://github.com/OpenEPaperLink/Tag_FW_EFR32xG22/blob/bea011e24d4bac65a920aeaf2c16e460aa4f0813/firmware/oepl_hw_abstraction.c#L190-L207

Debug output in this case is serial, 115200 8-N-1, routed to pin B2 which is available on the PCB pad labeled 'TX' (diagonally opposite corner of the GND pad). See picture ([source](https://fcc.report/FCC-ID/2AFWN-EL029F5C4C/6852661)) 
<img width="332" alt="Screenshot 2024-07-31 101927" src="https://github.com/user-attachments/assets/1560ff61-df60-4643-b1fd-d44476d865f2">

**Comment by stevew817** [comment]
@krikkirk I've created a new release with the fix for driving the third color on BWY tags, and logged a separate issue #3 for making them actually report as BWY to the AP. Closing this issue - feel free to create another one if you should encounter more troubles.

**Comment by krikkirk** [comment]
Thanks a ton for your detailed explanation!
